FROM node:18.17.1-alpine AS Build 
WORKDIR/app
COPY package*.json ./
RUN  npm install
RUN npx ngcc --properties es2023 browser module main --first-only --create-ivy-entry-points
COPY ..
RUN npm run Build
FROM nginx:stable
COPY --from=build
FROM nginx:stable
COPY --from=build
COPY --from=build /app/dist / securecapitaapp  /usr/share/nginx/html
EXPOSE 80

