export enum Role {
  User = 'User',
  Admin = 'Admin',
  MANAGER = "MANAGER",
  SUPER_ADMIN = "SUPER_ADMIN",
  STORESMANAGER = "STORESMANAGER",
  STOREASSISTANCE = "STOREASSISTANCE",
  ADMINMANAGER = "ADMINMANAGER"
}
